هذا هو تدفق عمل أساسي لمساعدتك على البدء في الإجراءات

الاسم                   :               سي

مراقبة عندما يعمل يعمل يعمل
على:
               يُخدّرُ ُ ُ مَنْ يَسْحبُ أَنْ تَطْلبَ الأحداثَ لكن فقط لفرع              "الرئيسي"
            دفع                 :
            الفروع                                    :              [ "الرئيسي" ]
            طلب سحب                  :
            الفروع                                    :              [ "الرئيسي" ]

              يُعلّكَ تَرْكضُ هذاَ يدوياً مِنْ العملِ يَجْعلُ هذا يَ            
            التدفق/إرسال                 :

:              :             تشغيل تشغيل العمل يتألف من وظيفة أو أكثر من وظائف يمكن أن تعمل بشكل متتابع أو بالتوازي
الوظائف:
              هذا التدفق يتضمن وظيفة واحدة تسمى             "البناء"
            بناء                  :
                نوع من العداء الذي سيتم العمل على            
            تشغيل                                   :             (ب) آخر

               :                              :            الخطوات تمثل سلسلة من المهام التي سيتم تنفيذها كجزء من العمل
            الخطوات                  :
                  تَرْدُ المستودعَكَ تحتِ GITHUB\_WORKSPACE، لذا وظيفتكِ يُمْكِنُ أَنْ تَصْولَ            
                 -            الاستخدامات                 :            الإجراءات/التحقق//v3

                 تشغيل قيادة واحدة باستخدام قذيفة الهاربين           
                 -            الاسم                 :            تشغيل سيناريو من خط واحد
           اركض                                  :           (ددإطّر مرحباً، أيها العالم!

                 تشغيل مجموعة من الأوامر باستخدام قذيفة العداء           
                -           الاسم                 :           تشغيل سيناريو متعدد الخطوط
           اركض                                  :           |
          (أ) يضاف إجراءات أخرى للبناء،          
        اختبار الصدى، ونشر مشروعك.        
